import type { IncomingMessage, ServerResponse } from 'node:http'

const allowedUrls = new Set([
  'https://medium.com/ux-user-experience-design-em-portugues/voluntariado-hands-on-conectando-a-pr%C3%A1tica-com-a-colabora%C3%A7%C3%A3o-4f1476f37d9c',
  'https://vagasux.com.br/voluntariado',
  'https://www.soujunior.tech/',
  'https://www.freehelper.com.br/',
  'https://www.worldpackers.com/pt-BR/',
  'https://todxs.org/voluntariado/',
  'https://ciclosdeux.com.br/',
  'https://www.hamburgadadobem.com.br/',
  'https://www.idealist.org/remote-volunteer-opportunities',
  'https://taprootfoundation.org/',
  'https://www.catchafire.org/',
  'https://www.techforgood.live/help-a-charity',
  'https://medium.com/aela/6-dicas-essenciais-para-montar-seu-portf%C3%B3lio-de-ux-design-205e551b3aa3',
  'https://brasil.uxdesign.cc/como-estruturar-um-case-para-portf%C3%B3lio-de-ux-ui-e-impressionar-recrutadores-62266ee50839',
  'https://dribbble.com/stories/2020/03/11/ultimate-guide-getting-hired-ux-design',
  'https://medium.com/ux-user-experience-design-em-portugues/uma-reflex%C3%A3o-sobre-portfolios-cursos-e-anseios-por-empregos-9b19cf51d03',
  'https://brasil.uxdesign.cc/como-montar-um-portf%C3%B3lio-de-ux-se-eu-ainda-n%C3%A3o-trabalho-com-ux-c5ec6434de20',
  'https://projectportfoliocanvas.com/',
  'https://www.tifolio.com.br/',
  'https://www.linkedin.com/pulse/canvas-portf%25C3%25B3lio-ux-um-modelo-para-estruturar-de-do-grochewski/',
  'https://www.uxtools.co/challenges',
  'https://sharpen.design/',
  'http://www.whatshouldidesign.com/',
  'https://productdesigninterview.com/weekly-ux-product-design-exercise',
  'https://designercize.com/',
  'https://www.briefsup.com/',
  'https://www.designassignments.com/',
  'https://goodbrief.io/',
  'https://drawerrr.com/',
  'https://www.uicoach.io/',
  'https://www.briefz.biz/',
  'https://fakeclients.com/ux',
  'https://brasil.uxdesign.cc/onde-criar-portf%C3%B3lio-de-design-an%C3%A1lise-e-refer%C3%AAncias-a77a3c08b8c8',
  'https://uxfol.io/',
  'https://super.so/',
  'https://bubble.io/',
  'https://portfolio.adobe.com/sites',
  'https://www.semplice.com/',
  'https://pt.squarespace.com/',
  'https://readymag.com/',
  'https://pt.wix.com/',
  'https://designdobrasil.co/',
  'https://rafa-luve.raindrop.page/portfolio-examples-57795513',
  'https://vagasux.substack.com/p/vagasux-news-23-abril-folio',
  'https://vagasux.substack.com/p/vagasux-news-24-may-the-portfolio',
  'https://www.nngroup.com/articles/answer-ux-job-interview-questions/',
  'https://blog.uxfol.io/ux-resume-what-to-include/',
  'https://blog.uxfol.io/ux-resume-layout/',
  'https://blog.uxfol.io/ux-designer-portfolio/',
  'https://blog.uxfol.io/ux-portfolio-presentation/',
  'https://www.atados.com.br/',
  'https://www.linkedin.com/posts/nobrepires_designprinciples-ats-designbasics-ugcPost-7216454878913585152-xEC2?utm_source=share&utm_medium=member_android',
  'https://resume.io/ats-resume-checker',
  'https://bettercv.com/ats',
  'https://create.microsoft.com/pt-br/templates/curr%C3%ADculos-e-cartas-de-apresenta%C3%A7%C3%A3o-do-sistema-de-rastreamento-de-candidatos-(ats)',
  'https://blog.uxfol.io/product-designer-resume/',
  'https://resumeworded.com/ux-designer-resume-examples',
  'https://vagasux.com.br/guia/tipo/eventos',
  'https://vagasux.com.br/comunidade',
  'https://cantunsee.space/',
  'https://mobbin.com/',
  'https://screensdesign.com/',
  'https://pageflows.com/',
  'https://webframe.xyz/',
  'https://theappfuel.com/',
  'https://chamjo.design/',
  'https://pttrns.com/',
  'https://land-book.com/',
  'https://scrnshts.club/',
  'https://interfaceingame.com/',
  'https://www.unsection.com/',
  'https://refero.design/',
  'https://element.eleme.io/#/en-US',
  'https://collectui.com/',
  'https://www.producthunt.com/',
  'https://designmunk.com/',
  'https://www.lapa.ninja/',
  'https://www.figma.com/best-practices/',
  'https://awesomefigmatips.com/',
  'https://www.figma.com/resource-library/design-basics/',
  'https://www.figma.com/best-practices/tips-and-tricks/',
  'https://www.figma.com/best-practices/team-file-organization/',
  'https://www.figma.com/release-notes/',
  'https://www.figma.com/community',
  'https://www.cursae.com.br/play-course/figma-criando-interfaces-do-zero-ate-o-prototipo-final/introducao-ao-figma',
  'https://friends.figma.com/',
  'https://friends.figma.com/sao-paulo/',
  'https://x.com/figma',
  'https://www.figma.com/blog/',
  'https://config.figma.com/',
  'https://framer.com/',
  'https://icons8.com.br/lunacy',
  'https://webflow.com/',
  'https://www.sketch.com/',
  'https://www.axure.com/',
  'https://www.uxpin.com/',
  'http://marvelapp.com/',
  'https://penpot.app/',
  'https://www.protopie.io/',
  'https://www.canva.com/pt_br/',
  'https://chatgpt.com/pt-BR/',
  'https://gemini.google.com/',
  'https://claude.ai/login',
  'https://copilot.microsoft.com/',
  'https://www.perplexity.ai/',
  'https://www.deepseek.com/',
  'https://cursor.com/',
  'https://claude.com/product/claude-code',
  'https://v0.app/',
  'https://lovable.dev/pt-br',
  'https://bolt.new/',
  'https://n8n.io/',
  'https://www.make.com/en',
  'https://zapier.com/',
  'https://pipedream.com/',
  'https://kling.ai/',
  'https://hailuoai.video/',
  'https://www.synthesia.io/pt-br',
  'https://www.bing.com/images/create/ai-image-generator',
  'https://lumalabs.ai/app',
  'https://lensa.app/',
  'https://tomeapp.ai/',
  'https://pair.withgoogle.com/guidebook/',
  'https://www.openui.com/',
  'https://ui.shadcn.com/',
  'https://styles.refero.design/',
  'https://learnprompting.org/pt/docs/introduction',
  'https://futuretools.io/',
  'https://quillbot.com/',
  'https://punkmetrics.com/skills-de-design-para-claude-code/',
  'http://guidetouxr.com/',
  'https://www.uxlibrary.org/',
  'https://lawsofux.com/',
  'https://www.reallygoodux.io/',
  'https://littlebigdetails.com/',
  'https://medium.com/aela/jornada-do-usu%C3%A1rio-o-que-%C3%A9-e-sua-import%C3%A2ncia-em-ux-design-f8ac0cb025ca',
  'https://medium.com/aela/teste-de-usabilidade-o-que-voc%C3%AA-precisa-saber-39a36343d9a6',
  'https://maze.design/',
  'https://www.useberry.com/',
  'https://www.userlytics.com/',
  'https://uxpressia.com/',
  'https://toolbox.hyperisland.com/',
  'https://www.designkit.org/methods.html',
  'https://usepastel.com/',
  'https://userbitapp.com/',
  'https://answerthepublic.com/',
  'https://brasil.uxdesign.cc/open-card-sorter-em-busca-de-uma-ferramenta-de-card-sorting-para-chamar-de-nossa-b821a41d3fa4',
  'https://dovetailapp.com/',
  'https://www.hubspot.com/make-my-persona',
  'https://talebook.io/',
  'https://pt.surveymonkey.com/mp/sample-size-calculator/',
  'https://brasil.uxdesign.cc/ux-writing-o-que-%C3%A9-e-por-onde-come%C3%A7ar-ace250650187',
  'https://brasil.uxdesign.cc/ux-writing-muito-al%C3%A9m-das-palavras-9669af8ed76e',
  'https://medium.com/uxcopy-co/as-muitas-poss%C3%ADveis-facetas-de-ux-writing-4ce32648c6c1',
  'https://medium.com/@camilagaidarji/ux-writing-copywriting-e-web-writing-s%C3%A3o-escritas-completamente-diferentes-4e3d516abc33',
  'https://goodmicrocopy.com/',
  'https://medium.com/@aleperiardux/como-criar-um-portf%C3%B3lio-de-ux-writer-em-2025-passo-a-passo-com-dicas-exemplos-e-links-%C3%BAteis-862780a291a8',
  'https://brasil.uxdesign.cc/como-a-colabora%C3%A7%C3%A3o-d%C3%A1-vida-as-palavras-fbb5c5a59659',
  'https://www.speakhuman.today/',
  'https://dailyuxwriting.com/',
  'https://clarice.ai/',
  'https://brasil.uxdesign.cc/reposit%C3%B3rio-de-ux-writing-conte%C3%BAdos-e-refer%C3%AAncias-da-%C3%A1rea-em-um-s%C3%B3-lugar-a201dcf22a41',
  'https://docs.google.com/spreadsheets/d/1Vbz0oagCqE3a2jUu0kblfBEz8mEXSSsQuAJIHnCmNyc/edit?usp=sharing',
  'https://blog.usejournal.com/a-mega-list-of-ux-writing-resources-d9f200d6dfde',
  'https://uxdesign.cc/best-ux-writing-portfolios-2019-update-7e6a066631af',
  'https://codelabs.developers.google.com/codelabs/material-communication-guidance?utm_source=google-io21&utm_medium=referral&utm_campaign=io21-resources#0',
  'https://medium.com/@paulodasilva233/guias-de-voz-tom-em-portugues-db47f7624ab1',
  'https://medium.com/design-contaazul/como-come%C3%A7amos-a-estruturar-ux-writing-na-conta-azul-com-um-guia-de-reda%C3%A7%C3%A3o-5dd516315ee3',
  'https://medium.com/vindi/voz-e-tom-da-vindi-como-come%C3%A7amos-a-construir-o-nosso-guia-11c1692c15da',
  'https://docs.google.com/spreadsheets/d/1vXDJ4CcRSCP_FGgdrAJgcKdU9KuR7gFDyWfMH3JFrJ0/edit?usp=sharing',
  'https://www.nngroup.com/articles/design-systems-101/',
  'https://www.figma.com/blog/design-systems-101-what-is-a-design-system/',
  'https://medium.com/meiuca/2-seu-design-system-%C3%A9-um-produto-1018e81be045',
  'https://medium.com/airbnb-design/building-a-visual-language-behind-the-scenes-of-our-airbnb-design-system-224748775e4e',
  'https://medium.com/quintoandar-design/construindo-design-systems-inclusivos-11143a16b2fb',
  'https://medium.com/meiuca/3-o-que-%C3%A9-design-ops-muita-coisa-5d23bafcc7bd',
  'https://documenting.design/',
  'https://principles.design/',
  'https://designsystemchecklist.com/',
  'https://www.uiguideline.com/',
  'https://www.zeroheight.com/',
  'https://www.supernova.io/',
  'https://storybook.js.org/',
  'https://specifyapp.com/',
  'https://www.duetds.com/designers/',
  'https://www.designsystems.com/',
  'https://designsystemsrepo.com/',
  'https://designsystemsbrasileiros.com/',
  'https://heydesign.systems/',
  'https://www.carbondesignsystem.com/',
  'https://polaris.shopify.com/',
  'https://atlassian.design/',
  'https://spectrum.adobe.com/',
  'https://contaazul.design/',
  'https://bold.bridge.ufsc.br/pt/',
  'https://playbook.ebay.com/',
  'https://whocanuse.com/',
  'https://learnui.design/tools/accessible-color-generator.html?colors=ff9f2f',
  'http://projects.susielu.com/viz-palette',
  'http://contrast-grid.eightshapes.com/',
  'https://colourcontrast.cc/',
  'https://leonardocolor.io/#',
  'https://colorffy.com/',
  'https://www.shadegenerator.com/',
  'https://www.radix-ui.com/colors',
  'https://colors.muz.li/',
  'https://colorleap.app/home',
  'https://picular.co/',
  'https://material.io/tools/color/#!/',
  'https://colourco.de/',
  'http://paletton.com/',
  'https://duotone.shapefactory.co/',
  'https://colorsupplyyy.com/app/',
  'https://flatuicolors.com/',
  'https://www.webdesignrankings.com/resources/lolcolors/',
  'https://colormixer.web.app/',
  'https://color.adobe.com/pt/',
  'https://coolors.co/',
  'https://hihayk.github.io/scale/',
  'https://www.mshr.app/create/new',
  'https://csshero.org/mesher/',
  'https://uigradients.com/',
  'https://mycolor.space/',
  'https://cssgradient.io/',
  'https://www.grabient.com/',
  'https://mobilepalette.colorion.co/',
  'https://sketchsheets.com/',
  'https://gridprint.in/',
  'https://sneakpeekit.com/',
  'https://uiprint.co/',
  'https://www.typewolf.com/',
  'https://fontjoy.com/',
  'https://fonts.google.com/',
  'https://fonts.adobe.com/',
  'https://www.fontsquirrel.com/',
  'https://prowebtype.com/',
  'https://type.method.ac/',
  'https://justmytype.co/',
  'https://fontsinuse.com/',
  'https://uncut.wtf/',
  'https://www.youtube.com/playlist?list=PLKbAmHQYDSaNodtj4fMHb3BJBOag7JC81',
  'https://thenounproject.com/',
  'https://www.streamlineicons.com/',
  'https://iconic.app/',
  'https://fonts.google.com/icons',
  'https://fontawesome.com/',
  'https://heroicons.com/',
  'https://orioniconlibrary.com/',
  'https://icomoon.io/',
  'https://icons8.com/line-awesome',
  'https://nucleoapp.com/',
  'https://www.flaticon.com/',
  'https://fontello.com/',
  'https://iconset.io/',
  'https://storytale.io/',
  'https://blush.design/',
  'https://www.figma.com/community/file/842934129022914364',
  'https://www.ls.graphics/illustrations',
  'https://control.rocks/',
  'https://icons8.com/illustrations',
  'https://undraw.co/illustrations',
  'https://www.drawkit.io/',
  'https://www.humaaans.com/',
  'https://stubborn.fun/',
  'https://fresh-folk.com/',
  'https://www.opendoodles.com/',
  'https://www.openpeeps.com/',
  'https://products.ls.graphics/wrrooom',
  'https://www.pixeltrue.com/free-illustrations',
  'https://sapiens.ui8.net/',
  'https://medium.com/@issarahaj/creating-usability-with-motion-the-ux-in-motion-manifesto-5f5e629f10ff',
  'https://brasil.uxdesign.cc/princ%C3%ADpios-b%C3%A1sicos-do-motion-design-da-disney-x-o-digital-parte-01-6ba499c24b08',
  'https://stephaniewalter.design/blog/enhancing-user-experience-with-css-animations/',
  'https://lottiefiles.com/',
  'https://airbnb.design/lottie/',
  'https://drawer.design/',
  'https://icons8.com/animated-icons',
  'https://cliply.co/',
  'https://www.framer.com/motion/',
  'https://www.figma.com/motion/',
  'https://useanimations.com/',
  'https://potlabicons.com/',
  'https://loading.io/',
  'https://rive.app/',
  'https://www.phase.com/',
  'https://creator.lottiefiles.com/',
  'https://www.svgator.com/',
  'https://principleformac.com/',
  'https://community.phase.com/',
  'https://uxmotiondesign.com/',
  'https://maxst.icons8.com/vue-static/landings/lunacy-new/opengraph-lunacy.jpg',
  'https://www.sketch.com/images/metadata/pages/home.jpg',
  'https://www.axure.com/images/2025/04/og-image.png',
  'https://files.uxpin.com/marketing-assets/hEANM0hTqezomJsApfaQ.webp',
  'https://marvelapp.com/static/workshop-nav@2x-7ec05d5fe3d476739e3d47833e3f8956-c4bfe.jpg',
  'https://miro.com/',
  'https://miro.com/miroverse/',
  'https://www.mural.co/',
  'https://whimsical.com/',
  'https://www.mindmeister.com/',
  'https://milanote.com/',
  'https://witeboard.com/',
  'https://www.flowmapp.com/',
  'https://www.figma.com/pt-br/figjam/',
  'https://brasil.uxdesign.cc/uma-breve-introdu%C3%A7%C3%A3o-a-acessibilidade-a82d61e72e75',
  'https://medium.com/tableless/acessibilidade-no-design-de-intera%C3%A7%C3%A3o-exemplos-e-recomenda%C3%A7%C3%B5es-86c059ef9e2f',
  'https://medium.com/ladies-that-ux-br/acessibilidade-e-produ%C3%A7%C3%A3o-de-conte%C3%BAdo-ux-913c4c55847c',
  'http://designinclusivo.com/',
  'http://acessibilida.de/',
  'https://guia-wcag.com/',
  'http://acessibilidadetoolkit.com/',
  'https://gaia.wiki.br/',
  'https://mwpt.com.br/',
  'https://accessibility-for-teams.com/',
  'https://digital.gov/guides/accessibility-for-teams/ux-design/',
  'https://moritzgiessmann.de/accessibility-cheatsheet/',
  'https://spectrum.adobe.com/page/inclusive-design/',
  'https://www.funkify.se/',
  'http://accessibility.voxmedia.com/',
  'https://gerireid.com/wcag-for-designers.html',
  'https://accessibility.blog.gov.uk/2016/09/02/dos-and-donts-on-designing-for-accessibility/',
  'https://www.figma.com/file/RWGgrLLjkcDndL7WTbHcHf/A11y-Annotation-Kit-(Community)?node-id=37%3A0',
  'https://docs.google.com/presentation/d/1IYcSZtK-XcYO4B9t6QCbaQI9dU33I9FZTSjitGLLc-o/edit?usp=sharing',
  'https://w3c.br/web-para-todos/cartilhas-de-acessibilidade-na-web/',
  'https://d16zac8h4kza33.cloudfront.net/ebook-marketing-profissionais-com-deficiencia/eBook-marketing-profissionais-com-deficiencia-resultados-digitais.pdf',
  'https://speechnotes.co/pt/',
  'https://play.google.com/store/apps/details?id=com.google.audio.hearing.visualization.accessibility.scribe',
  'https://captioner.live/',
  'https://woliveiras.com.br/linguagem-neutra',
  'https://github.com/woliveiras/linguagem-neutra-dev',
  'https://brasil.uxdesign.cc/m%C3%A9tricas-de-ux-por-onde-come%C3%A7ar-54fa7513e5e0',
  'https://brasil.uxdesign.cc/a-relacao-entre-ux-e-metricas-acompanhamento-pratico-de-metricas-d4c68a1522a4',
  'https://brasil.uxdesign.cc/guia-basico-de-estudos-sobre-metricas-de-ux-49cf5fc71ee6',
  'https://brasil.uxdesign.cc/quais-sao-as-metricas-de-ux-e-como-usa-las-ea21774778a1',
  'https://brasil.uxdesign.cc/m%C3%A9tricas-de-cx-que-todo-ux-deve-conhecer-5a432ded712b',
  'https://uxpilot.ai/blogs/ux-metrics',
  'https://clarity.microsoft.com/',
  'https://plausible.io/',
  'https://www.hotjar.com/pt-BR/',
  'https://youtu.be/gPH5hbdLaSI?si=INtwn_zLxdVRHtXm',
  'https://youtu.be/owbNt7RXJYk?si=yudDXCZ0KBPT4SAM',
  'https://youtu.be/1sT4T19OX6Q?si=58-uj5Bo5S3-iWZF',
  'https://youtu.be/ieD21pE9JTY?si=j6UgptosulgCRnPx',
  'https://medium.com/@orenatopaixao/ux-%C3%A9-pra-todo-mundo-ser%C3%A1-ed4bb62deae9',
  'https://brasil.uxdesign.cc/indo-al%C3%A9m-da-hashtag-a-real-import%C3%A2ncia-da-diversidade-na-tecnologia-6c358cd5e9fd',
  'https://brasil.uxdesign.cc/diversidade-em-times-de-produto-23ae95257d62',
  'https://brasil.uxdesign.cc/ux-design-como-ferramenta-na-producao-de-diversidade-fe0fba9bebe1',
  'https://youtu.be/rQHJhaP2L00',
  'https://github.com/woliveiras/linguagem-neutra-dev',
  'https://orientando.org/',
  'https://brazilianswho.design/',
  'https://www.orgulhotech.com.br/',
  'https://www.atados.com.br/ong/ong-lgbt',
  'https://www.todasasletras.org/',
  'https://maisdiversidade.com.br/',
  'https://www.nohssomos.com.br/',
  'https://diversitera.com/',
  'http://www.pretux.com.br/',
  'https://docs.google.com/spreadsheets/d/1R5VOdDKOZfvClbe-TcWTH0oSe5hm23dl05h3xUoBAlg/edit?usp=sharing',
  'https://womenwho.design/',
  'https://blackswho.design/',
  'https://queerdesign.club/',
  'https://www.latinxswhodesign.com/',
  'https://humanebydesign.com/',
  'https://visualhunt.com/',
  'https://pt.shopify.com/burst',
  'https://photos.icons8.com/',
  'https://unsplash.com/',
  'https://www.pichastock.com/',
  'https://stock.adobe.com/br/search?serie_id=124394558&load_type=see_more&prev_url=detail',
  'https://everypixel.com/',
  'https://publicdomainarchive.com/',
  'https://br.freepik.com/',
  'https://stock.adobe.com/br/free',
  'https://www.pexels.com/',
  'https://www.brasilcoms.com.br/',
  'https://www.nappy.co/',
  'https://www.flickr.com/photos/149801498@N06/',
  'https://affecttheverb.com/collection/',
  'https://genderphotos.vice.com/',
  'https://ygb.black/',
  'https://unsplash.com/s/photos/plus-size',
  'https://www.4devs.com.br/',
  'https://undesign.learn.uno/generator/',
  'https://br.lipsum.com/',
  'http://www.cutedrop.com.br/2016/03/lorem-ipsum-de-imagens-geradores-de-fotos-gratuitas-para-usar-nos-seus-layouts/',
  'http://feminipsum.com.br/',
  'http://www.zombieipsum.com/',
  'https://mussumipsum.com/',
  'http://www.cupcakeipsum.com/',
  'http://www.catipsum.com/',
  'https://satoristudio.net/delorean-ipsum/',
  'https://slipsum.com/',
  'https://vlad-saling.github.io/star-trek-ipsum/',
  'https://hipsum.co/',
  'https://silviosantosipsum.com/',
  'https://siliconvalleyjobtitlegenerator.tumblr.com/',
  'https://designtitles.com/',
  'https://www.notion.so/',
  'https://raindrop.io/',
  'https://meetfranz.com/',
  'https://scribehow.com/',
  'https://doodle.com/en/',
  'https://www.mentimeter.com/',
  'https://calendly.com/',
  'https://alternativeto.net/',
  'https://obsproject.com/',
  'https://www.webex.com/pt/index.html',
  'https://www.araelium.com/screenflick-mac-screen-recorder',
  'https://chrome.google.com/webstore/detail/screen-and-webcam-recorde/jiihcciniecimeajcniapbngjjbonjan',
  'https://recordscreen.io/',
  'https://www.useloom.com/',
  'https://overframe.xyz/',
  'https://lookback.io/',
  'https://www.awesomescreenshot.com/',
  'https://getkap.co/',
  'http://recordit.co/',
  'https://www.inspectlet.com/',
  'https://www.fullstory.com/',
  'https://www.smartlook.com/pt/',
  'https://www.telestream.net/screenflow/overview.htm',
  'https://play.google.com/store/apps/details?id=com.rsupport.mvagent&hl=pt_BR',
])

function getAttribute(tag: string, attribute: string) {
  const match = tag.match(
    new RegExp(`${attribute}\\s*=\\s*["']([^"']+)["']`, 'i'),
  )
  return match?.[1]?.trim() ?? null
}

function getOpenGraphImage(html: string, pageUrl: string) {
  const metaTags = html.match(/<meta\b[^>]*>/gi) ?? []

  for (const tag of metaTags) {
    const key = getAttribute(tag, 'property') ?? getAttribute(tag, 'name')
    if (key?.toLowerCase() !== 'og:image') continue

    const content = getAttribute(tag, 'content')
    if (!content) continue

    try {
      return new URL(content, pageUrl).href
    } catch {
      return null
    }
  }

  for (const tag of metaTags) {
    const key = getAttribute(tag, 'property') ?? getAttribute(tag, 'name')
    if (key?.toLowerCase() !== 'twitter:image') continue

    const content = getAttribute(tag, 'content')
    if (!content) continue

    try {
      return new URL(content, pageUrl).href
    } catch {
      return null
    }
  }

  return null
}

async function getUnfurlImage(sourceUrl: string) {
  try {
    const params = new URLSearchParams({ url: sourceUrl, meta: 'true' })
    const response = await fetch(`https://api.microlink.io/?${params}`, {
      signal: AbortSignal.timeout(8000),
    })
    if (!response.ok) return null

    const data = (await response.json()) as {
      data?: { image?: { url?: unknown } }
    }

    return typeof data.data?.image?.url === 'string'
      ? data.data.image.url
      : null
  } catch {
    return null
  }
}

function sendJson(
  response: ServerResponse,
  body: { imageUrl: string | null },
  cacheControl: string,
  statusCode = 200,
) {
  response.statusCode = statusCode
  response.setHeader('Content-Type', 'application/json; charset=utf-8')
  response.setHeader('Cache-Control', cacheControl)
  response.end(JSON.stringify(body))
}

export default async function handler(
  request: IncomingMessage,
  serverResponse: ServerResponse,
) {
  if (request.method !== 'GET') {
    serverResponse.statusCode = 405
    serverResponse.end('Method not allowed')
    return
  }

  const sourceUrl = new URL(
    request.url ?? '/',
    `https://${request.headers.host ?? 'vagasux.vercel.app'}`,
  ).searchParams.get('url')
  if (!sourceUrl || !allowedUrls.has(sourceUrl)) {
    serverResponse.statusCode = 400
    serverResponse.end('Link não autorizado')
    return
  }

  let imageUrl: string | null = null

  try {
    const fetchedPage = await fetch(sourceUrl, {
      headers: {
        Accept: 'text/html,application/xhtml+xml',
        'User-Agent': 'VagasUX Link Preview/1.0',
      },
      signal: AbortSignal.timeout(5000),
    })

    if (fetchedPage.ok) {
      imageUrl = getOpenGraphImage(
        await fetchedPage.text(),
        fetchedPage.url,
      )
    }
  } catch {}

  if (!imageUrl) imageUrl = await getUnfurlImage(sourceUrl)

  sendJson(
    serverResponse,
    { imageUrl },
    imageUrl
      ? 'public, s-maxage=86400, stale-while-revalidate=604800'
      : 'public, s-maxage=3600',
  )
}
