import { Link } from 'react-router-dom'
import { Button } from '@/components/ui/button'
import { GuiaLinkPreviewCard } from '@/components/guia/GuiaLinkPreviewCard'
import { GuiaVideoCard } from '@/components/guia/GuiaVideoCard'
import { getGuiaGlossarioEntryById } from '@/data/guiaGlossario'
import { guiaTemaMetricsLinks } from '@/data/guiaTemaMetricsLinks'
import { guiaVideos } from '@/data/guiaVideos'
import { guiaRoutes } from '@/lib/guiaRoutes'
export function GuiaTemaMetricsPageContent(){const e=getGuiaGlossarioEntryById('metrica');const guiaMetricVideos=guiaVideos.filter(v=>v.context.includes('Métricas')).sort((a,b)=>new Date(b.addedAt??0).getTime()-new Date(a.addedAt??0).getTime()).slice(0,4);return <div className="mt-8 w-full"><header><div className="flex items-center gap-3"><span className="text-3xl">📊</span><h1 className="text-3xl font-black text-neutral-500 md:text-4xl">Métricas</h1></div></header>{e?<section className="mt-10 rounded-3xl border border-brand-200/60 bg-brand-100/35 p-6"><h2 className="text-base font-black text-neutral-500">O que é?</h2><div className="mt-2 space-y-3 text-sm text-neutral-400">{e.whatIs.map(x=><p key={x}>{x}</p>)}</div><Button asChild variant="guia-outline" className="mt-5"><Link to={`${guiaRoutes.glossario}#metrica`}>Ver no glossário completo</Link></Button></section>:null}<div className="mt-10 space-y-12">{guiaTemaMetricsLinks.map(s=><section key={s.title}><h2 className="text-xl font-black text-neutral-500">{s.title}</h2><ul className="mt-5 grid gap-4 lg:grid-cols-2">{s.links.map(l=><li key={l.url}><GuiaLinkPreviewCard link={l} className="h-full"/></li>)}</ul></section>)}</div><section className="mt-12"><div className="flex items-center justify-between gap-4"><h2 className="text-xl font-black text-neutral-500">Vídeos de Métricas</h2><Button asChild variant="guia-outline"><Link to="/guia/tipo/videos?contexto=Métricas">Ver todos os vídeos</Link></Button></div><ul className="mt-5 grid grid-cols-2 gap-5 sm:grid-cols-3 lg:grid-cols-4">{guiaMetricVideos.map(v=><li key={v.id}><GuiaVideoCard video={v} className="h-full"/></li>)}</ul></section><div className="mt-12 grid gap-5 md:grid-cols-2"><section className="rounded-3xl border border-neutral-500/10 bg-neutral-100 p-6"><h2 className="text-xl font-black text-neutral-500">Procurando por livros de métricas?</h2><Button asChild variant="guia-outline" className="mt-5"><Link to="/guia/tipo/livros?contexto=Métricas">Explorar livros</Link></Button></section><section className="rounded-3xl border border-neutral-500/10 bg-neutral-100 p-6"><h2 className="text-xl font-black text-neutral-500">Procurando por cursos de métricas?</h2><Button asChild variant="guia-outline" className="mt-5"><Link to={`${guiaRoutes.cursos}?tema=Métricas#guia-cursos-filtros`}>Explorar cursos</Link></Button></section></div></div>}
